version: '3.3'
services:
  db:
    # add platform linux/amd64
    platform: linux/amd64
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_DATABASE: 'pet_hospital'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin1'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'hifrpupp'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'etjapwlm'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

